### ISSUE TITLE
Versions 1.0.37 and 1.0.38 of the npm package are missing package folder

### ISSUE THREAD

**Issue by dschenkelman** [Zokrates/ZoKrates#1082]
## Description
When running the Node.js sample with versions 1.0.37 and 1.0.38 the following error occurs:
```➜  zokrates git:(master) ✗ node index.js
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './pkg/index.js'
Require stack:
- $workingDir/node_modules/zokrates-js/node/index.js
- $workingDir/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at initialize ($workingDir/node_modules/zokrates-js/node/index.js:7:19)
    at Object.<anonymous> ($workingDir/index.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '$workingDir/node_modules/zokrates-js/node/index.js',
    '$workingDir/index.js'
  ]
}
```

The `.pkg` folder is missing in those releases:
![image](https://user-images.githubusercontent.com/3376731/148597656-8e51fa2f-59e2-493b-be8b-e8d69b8589ff.png)

but is present in 1.0.36.
![image](https://user-images.githubusercontent.com/3376731/148597619-19283e2b-1152-4c92-b9b9-c97abe2b08b2.png)

## Environment

- Operating system: macOS 11.6.2
- Node version:v16.13.1
- npm version: 8.1.2

## Steps to Reproduce
Run the sample from here: https://zokrates.github.io/toolbox/zokrates_js.html.

**Comment by dark64** [comment]
Hey @dschenkelman, thanks for the report! It seems some unexpected things are happening in our CI pipeline regarding `zokrates-js`, which resulted in incomplete packages being pushed to npm. We will try to resolve this asap, until then you can fallback to `1.0.36`
