### ISSUE TITLE
panicked at /src/zokrates_ark/src/groth16.rs:42:18: called `Result::unwrap()` on an `Err` value: IoError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })

### ISSUE THREAD

**Issue by SagarKarmoker** [Zokrates/ZoKrates#1363]
## Description
panicked at /src/zokrates_ark/src/groth16.rs:42:18:
called `Result::unwrap()` on an `Err` value: IoError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (file:///W:/U%20Disk/CSE400/Code/SmartContractTest/kycbackend/node_modules/zokrates-js/wasm.js:402:17)
    at wasm://wasm/0d2249e6:wasm-function[23821]:0x301108a
    at wasm://wasm/0d2249e6:wasm-function[39798]:0x33a1f00
    at wasm://wasm/0d2249e6:wasm-function[32366]:0x32d5a59
    at wasm://wasm/0d2249e6:wasm-function[34085]:0x3320e52
    at wasm://wasm/0d2249e6:wasm-function[37363]:0x3381def
    at wasm://wasm/0d2249e6:wasm-function[38515]:0x33996cf
    at wasm://wasm/0d2249e6:wasm-function[35779]:0x33586d3
    at wasm://wasm/0d2249e6:wasm-function[20399]:0x2e4ec2c
    at wasm://wasm/0d2249e6:wasm-function[17484]:0x2c75f07

Error in generating proof: RuntimeError: unreachable
    at wasm://wasm/0d2249e6:wasm-function[32366]:0x32d5a7f
    at wasm://wasm/0d2249e6:wasm-function[34085]:0x3320e52
    at wasm://wasm/0d2249e6:wasm-function[37363]:0x3381def
    at wasm://wasm/0d2249e6:wasm-function[38515]:0x33996cf
    at wasm://wasm/0d2249e6:wasm-function[35779]:0x33586d3
    at wasm://wasm/0d2249e6:wasm-function[20399]:0x2e4ec2c
    at wasm://wasm/0d2249e6:wasm-function[17484]:0x2c75f07
    at wasm://wasm/0d2249e6:wasm-function[2810]:0x14ee021
    at Module.generate_proof (file:///W:/U%20Disk/CSE400/Code/SmartContractTest/kycbackend/node_modules/zokrates-js/wasm.js:218:10)
    at Object.generateProof (file:///W:/U%20Disk/CSE400/Code/SmartContractTest/kycbackend/node_modules/zokrates-js/index.js:92:26)
RuntimeError: unreachable
    at wasm://wasm/0d2249e6:wasm-function[32366]:0x32d5a7f
    at wasm://wasm/0d2249e6:wasm-function[34085]:0x3320e52
    at wasm://wasm/0d2249e6:wasm-function[37363]:0x3381def
    at wasm://wasm/0d2249e6:wasm-function[38515]:0x33996cf
    at wasm://wasm/0d2249e6:wasm-function[35779]:0x33586d3
    at wasm://wasm/0d2249e6:wasm-function[20399]:0x2e4ec2c
    at wasm://wasm/0d2249e6:wasm-function[17484]:0x2c75f07
    at wasm://wasm/0d2249e6:wasm-function[2810]:0x14ee021
    at Module.generate_proof (file:///W:/U%20Disk/CSE400/Code/SmartContractTest/kycbackend/node_modules/zokrates-js/wasm.js:218:10)
    at Object.generateProof (file:///W:/U%20Disk/CSE400/Code/SmartContractTest/kycbackend/node_modules/zokrates-js/index.js:92:26)

## Environment

- Compiler version: 1.1.9
- Operating system: windows 10

**Comment by imilio** [comment]
Any solutions to this bug? just encountered the same

**Comment by dark64** [comment]
This occurs when the process of proving key deserialization fails, which can be due to several reasons:

- Passing it in an unexpected format (difficult to determine without reviewing your code),
- Executing the setup with a different engine, such as `bellman`, while attempting to generate proof with `ark` using  `bellman` artifacts,
- Version mismatch, where the setup is run on an older version of Zokrates.
