### ISSUE TITLE
Error while running setup phase

### ISSUE THREAD

**Issue by sameersubudhi** [Zokrates/ZoKrates#500]
Hi,

I was trying to run the setup phase on a ZoKrates program to generate the prover/verifier keys and thus the verifier contract. The code accepts multiple input parameters, some of which are field arrays. When making the field arrays private, I encounter the below error. There are no issues when the input field array is public. ZoKrates versions used: **v0.4.10** and **v0.5.0**.

**Sample test codes:**
```
def main(private field[5] a) -> (field):
    return a[0]
```

**Commands:**
- `zokrates compile --light -i test.code` or `zokrates compile --light -i test.zok`
- `zokrates setup --light`

**Error stack (on version 0.4.10):**
```
Performing setup...
WARNING: You are using the G16 scheme which is subject to malleability. See zokrates.github.io/reference/proving_schemes.html#g16-malleability for implications.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnconstrainedVariable', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: zokrates_core::proof_system::bn128::utils::bellman::Computation<zokrates_field::field::FieldPrime>::setup
  12: <zokrates_core::proof_system::bn128::g16::G16 as zokrates_core::proof_system::ProofSystem>::setup
  13: zokrates::cli
  14: zokrates::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  19: std::panicking::try
             at src/libstd/panicking.rs:275
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  22: main
  23: __libc_start_main
  24: <unknown>
```

**Error stack (on version 0.5.0):**
```
Performing setup...
WARNING: You are using the G16 scheme which is subject to malleability. See zokrates.github.io/reference/proving_schemes.html#g16-malleability for implications.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnconstrainedVariable', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55ee481f73da - backtrace::backtrace::libunwind::trace::h1e48a20fd8c00e78
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55ee481f73da - backtrace::backtrace::trace_unsynchronized::ha3529ce723adbcee
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55ee481f73da - std::sys_common::backtrace::_print_fmt::h8af0f3de30e6525c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55ee481f73da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hccc22ef69c236f5f
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55ee48218f6c - core::fmt::write::hcb7e7f6ddd656bfe
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55ee481f2657 - std::io::Write::write_fmt::h6c33e0621bf40a79
                               at src/libstd/io/mod.rs:1412
   6:     0x55ee481f998e - std::sys_common::backtrace::_print::hfdd90d4cd009ebe8
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55ee481f998e - std::sys_common::backtrace::print::h7433d2544b7ef8c5
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55ee481f998e - std::panicking::default_hook::{{closure}}::hff9b44de9e6c19e7
                               at src/libstd/panicking.rs:189
   9:     0x55ee481f9691 - std::panicking::default_hook::hc69137e056e73830
                               at src/libstd/panicking.rs:206
  10:     0x55ee481fa085 - std::panicking::rust_panic_with_hook::h56cd936fdb033c8f
                               at src/libstd/panicking.rs:469
  11:     0x55ee481f9c22 - std::panicking::continue_panic_fmt::h8a7037af81bd7386
                               at src/libstd/panicking.rs:376
  12:     0x55ee481f9b16 - rust_begin_unwind
                               at src/libstd/panicking.rs:303
  13:     0x55ee48215b9a - core::panicking::panic_fmt::hb815424fcb81826f
                               at src/libcore/panicking.rs:84
  14:     0x55ee48215c97 - core::result::unwrap_failed::h2796c78f8d661c62
                               at src/libcore/result.rs:1165
  15:     0x55ee4802d5fa - <zokrates_core::proof_system::bn128::g16::G16 as zokrates_core::proof_system::ProofSystem>::setup::h949974f2804a18ac
  16:     0x55ee47bb09d8 - zokrates::cli::ha3b5db58c97d35a8
  17:     0x55ee47babd9f - zokrates::main::h698cb05d58cc73c7
  18:     0x55ee47b707f3 - std::rt::lang_start::{{closure}}::h31974fa601941d4e
  19:     0x55ee481f9ab3 - std::rt::lang_start_internal::{{closure}}::h6d8c69ee4c317d9c
                               at src/libstd/rt.rs:48
  20:     0x55ee481f9ab3 - std::panicking::try::do_call::h6b2d27b56a1d7cff
                               at src/libstd/panicking.rs:288
  21:     0x55ee481fd84a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  22:     0x55ee481fa63d - std::panicking::try::h42476f95257c888c
                               at src/libstd/panicking.rs:267
  23:     0x55ee481fa63d - std::panic::catch_unwind::h3fda72ece6553178
                               at src/libstd/panic.rs:394
  24:     0x55ee481fa63d - std::rt::lang_start_internal::hd5f845e5899034eb
                               at src/libstd/rt.rs:47
  25:     0x55ee47bb5a42 - main
  26:     0x7f6fc4516b97 - __libc_start_main
  27:     0x55ee47b05c29 - <unknown>
  28:                0x0 - <unknown>
```

Best regards,
Sameer

**Comment by Schaeff** [comment]
Thanks a lot for this @sameersubudhi, we had something similar in the past, it seems to happen with arrays. I'll look into it.

**Comment by Schaeff** [comment]
I think I identified the issue, actually not related to arrays. It's just that bellman enforces all private variables to be used in the contraints. A more minimal example is:
```
def main(private field a) -> ():
   return
```

**Comment by Schaeff** [comment]
@JacobEberhardt what do you think here? Should we also enforce that? That would be another read-only static analysis step. Can you think of a case where a private value would be left unconstrained for a good reason?

**Comment by JacobEberhardt** [comment]
I do think that it would be helpful to enforce that in static analysis.
There are obvious use-cases where public inputs would not be used in the constraint system, e.g., nullifiers, but I cannot think of a case where this would hold true for private variables.

**Comment by sameersubudhi** [comment]
> I think I identified the issue, actually not related to arrays. It's just that bellman enforces all private variables to be used in the constraints. A more minimal example is:
> 
> ```
> def main(private field a) -> ():
>    return
> ```

@Schaeff Thank you for figuring out the underlying issue. I am now able to proceed further with minor fixes.

Another issue, unrelated but worth mentioning, is that the piece of code that compiles successfully on v0.4.10 gets killed on v0.5.0. My preliminary analysis shows that the compilation process uses at most 30,9% (under 10GB) of RAM on v0.4.10 but runs out of memory on v0.5.0. Total available RAM is 32GB. Probably, v0.5.0 also demands more CPU power than v0.4.10. Is this behaviour expected?
