### ISSUE TITLE
Setup panics if private argument is unused

### ISSUE THREAD

**Issue by dark64** [Zokrates/ZoKrates#554]
## Steps to Reproduce
Given the following code
```
// main.zok
def main(private field a) -> (field):
    return 1
```
1. `./zokrates compile --input main.zok`
2. `RUST_BACKTRACE=1 ./zokrates setup`

Setup panics with the following stack backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnconstrainedVariable', src/libcore/result.rs:1192:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:463
  11: rust_begin_unwind
             at src/libstd/panicking.rs:371
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1192
  14: zokrates_core::proof_system::bn128::utils::bellman::Computation<zokrates_field::field::FieldPrime>::setup
  15: <zokrates_core::proof_system::bn128::g16::G16 as zokrates_core::proof_system::ProofSystem>::setup
  16: zokrates::cli
  17: zokrates::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  22: std::panicking::try
             at src/libstd/panicking.rs:272
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: main
  26: __libc_start_main
  27: _start
```
This error makes sense but maybe handling the given scenario would be better instead of letting it panic? This only occurs with G16, no issues with PGHR13 and GM17 proving schemes.

**Comment by Schaeff** [comment]
Right, this is caused by bellman not allowing unused (= unconstrained) variables.
I guess it would make sense to apply this check ourselves during static analysis.

**Comment by dark64** [comment]
Just noticed this issue represents the same underlying issue described in https://github.com/Zokrates/ZoKrates/issues/500
