### ISSUE TITLE
Check panics when importing two functions from a file that contains errors

### ISSUE THREAD

**Issue by ErikP0** [Zokrates/ZoKrates#793]
## Description

`zokrates check` panics when checking a file that imports two functions from another file that contains errors.

## Environment

- Compiler version: be3865e9957e4e8509b227b9c82276c1b0d3edef (tag latest as of now)
- Operating system: linux

## Steps to Reproduce

File base.zok
```zokrates
from "./def" import f // two imports 
from "./def" import g

def main() -> field:
    return 1
```
File def.zok
```zokrates
def f() -> field:
    return 1

def g() -> field:
    bool a = 1 // <- this is an error in the imported function
    return 0
```
Run `RUST_BACKTRACE=full zokrates check --stdlib-path <path to stdlib> -i base.zok`

Panic + Stacktrace
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ZoKrates/zokrates_core/src/semantics.rs:435:34
stack backtrace:
   0:     0x55e161bcdb30 - std::backtrace_rs::backtrace::libunwind::trace::h4dee703919bfd40a
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55e161bcdb30 - std::backtrace_rs::backtrace::trace_unsynchronized::h457e839f1a563e20
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e161bcdb30 - std::sys_common::backtrace::_print_fmt::h86a55fb30f8393c8
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e161bcdb30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b3d6cac46d277e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55e161beb1cf - core::fmt::write::h127419eb46f2ecc9
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/fmt/mod.rs:1092:17
   5:     0x55e161bcace5 - std::io::Write::write_fmt::h6010cfbb4726588b
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/io/mod.rs:1578:15
   6:     0x55e161bcfb1b - std::sys_common::backtrace::_print::h79b4f9652330cc9d
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55e161bcfb1b - std::sys_common::backtrace::print::h330bb326a76af8cf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55e161bcfb1b - std::panicking::default_hook::{{closure}}::heb6a42a7d50a472e
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:208:50
   9:     0x55e161bcf5e3 - std::panicking::default_hook::h17e521ba6d68d6e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:225:9
  10:     0x55e161bd00cd - std::panicking::rust_panic_with_hook::h70db735e3a6e70cb
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:591:17
  11:     0x55e161bcfc97 - std::panicking::begin_panic_handler::{{closure}}::h777c71c8e5a7e25c
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:495:13
  12:     0x55e161bcdfec - std::sys_common::backtrace::__rust_end_short_backtrace::h3e9bf30168899554
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55e161bcfc29 - rust_begin_unwind
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
  14:     0x55e1610bf751 - core::panicking::panic_fmt::h5322a082d19786c3
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
  15:     0x55e1610bf69d - core::panicking::panic::haebb15b6842d6229
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:50:5
  16:     0x55e1617650b3 - zokrates_core::semantics::Checker::check_symbol_declaration::h5b71b8577dc2f725
  17:     0x55e1616dd5a3 - zokrates_core::semantics::Checker::check_module::h12e16c7048f811cd
  18:     0x55e1617720e6 - zokrates_core::semantics::Checker::check::h09941e7a824c8bc7
  19:     0x55e1611ed500 - zokrates_core::compile::check_with_arena::h9c1b1629fa4dacb2
  20:     0x55e1611ee6c3 - zokrates_core::compile::check::hee2fdb0d99f9966e
  21:     0x55e16132165b - zokrates::ops::check::exec::h2520beb1134b2f68
  22:     0x55e16182024b - zokrates::main::haf3f697dacbeac89
  23:     0x55e16167fbb6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc938c6bf01212dcd
  24:     0x55e16168033c - std::rt::lang_start::{{closure}}::hcff3cbe154022cb3
  25:     0x55e161bd04ca - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc915e668c7ca11
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:259:13
  26:     0x55e161bd04ca - std::panicking::try::do_call::h6b0f430d48122ddf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  27:     0x55e161bd04ca - std::panicking::try::h6ba420e2e21b5afa
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  28:     0x55e161bd04ca - std::panic::catch_unwind::h8366719d1f615eee
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  29:     0x55e161bd04ca - std::rt::lang_start_internal::h965c28c9ce06ee73
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/rt.rs:51:25
  30:     0x55e161820445 - main
  31:     0x7f53e1e80b25 - __libc_start_main
  32:     0x55e1610bfe3e - _start
  33:                0x0 - <unknown>
```
Expected: no panic

Note that if only one function is imported, `zokrates check` works as expected indicating the error. Running `zokrates check -i def.zok` behaves as expected as well.

**Comment by Schaeff** [comment]
This is already fixed on `develop`, thanks for flagging!
